#!/usr/bin/env bash
# Раскладка файлов комплекта по папкам фаз для GitHub-репозитория.
# Запускать из папки, где лежат все шаблоны и этот скрипт.
set -e

mkdir -p "01-iniciaciya-i-upravlenie"
mkdir -p "02-obsledovanie-i-analiz"
mkdir -p "03-proektirovanie"
mkdir -p "04-razrabotka-i-nastroyka"
mkdir -p "05-testirovanie"
mkdir -p "06-vnedrenie-i-ope"
mkdir -p "07-ekspluatacionnaya-dokumentaciya"
mkdir -p "08-zakrytie"

[ -f "sistemnyy_promt_proekta.md" ] && mv "sistemnyy_promt_proekta.md" "01-iniciaciya-i-upravlenie/" || echo "пропущен: sistemnyy_promt_proekta.md"
[ -f "Ustav_proekta_shablon.docx" ] && mv "Ustav_proekta_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Ustav_proekta_shablon.docx"
[ -f "Pasport_proekta_shablon.docx" ] && mv "Pasport_proekta_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Pasport_proekta_shablon.docx"
[ -f "Plan_upravleniya_proektom_shablon.docx" ] && mv "Plan_upravleniya_proektom_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Plan_upravleniya_proektom_shablon.docx"
[ -f "Reestr_steykholderov_shablon.xlsx" ] && mv "Reestr_steykholderov_shablon.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Reestr_steykholderov_shablon.xlsx"
[ -f "Organizacionnaya_struktura_proekta_shablon.docx" ] && mv "Organizacionnaya_struktura_proekta_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Organizacionnaya_struktura_proekta_shablon.docx"
[ -f "Matrica_RACI_artefakty.xlsx" ] && mv "Matrica_RACI_artefakty.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Matrica_RACI_artefakty.xlsx"
[ -f "Reestr_riskov_shablon.xlsx" ] && mv "Reestr_riskov_shablon.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Reestr_riskov_shablon.xlsx"
[ -f "Reestr_problem_Issue_Log.xlsx" ] && mv "Reestr_problem_Issue_Log.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Reestr_problem_Issue_Log.xlsx"
[ -f "Matrica_kommunikaciy.xlsx" ] && mv "Matrica_kommunikaciy.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Matrica_kommunikaciy.xlsx"
[ -f "Plan_upravleniya_izmeneniyami_shablon.docx" ] && mv "Plan_upravleniya_izmeneniyami_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Plan_upravleniya_izmeneniyami_shablon.docx"
[ -f "Reestr_zaprosov_na_izmenenie.xlsx" ] && mv "Reestr_zaprosov_na_izmenenie.xlsx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Reestr_zaprosov_na_izmenenie.xlsx"
[ -f "Kalendarnyy_plan_1C_MSProject.xml" ] && mv "Kalendarnyy_plan_1C_MSProject.xml" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Kalendarnyy_plan_1C_MSProject.xml"
[ -f "Plan_upravleniya_kachestvom_shablon.docx" ] && mv "Plan_upravleniya_kachestvom_shablon.docx" "01-iniciaciya-i-upravlenie/" || echo "пропущен: Plan_upravleniya_kachestvom_shablon.docx"
[ -f "Otchet_o_predproektnom_obsledovanii_shablon.docx" ] && mv "Otchet_o_predproektnom_obsledovanii_shablon.docx" "02-obsledovanie-i-analiz/" || echo "пропущен: Otchet_o_predproektnom_obsledovanii_shablon.docx"
[ -f "Opisanie_processov_As-Is_shablon.docx" ] && mv "Opisanie_processov_As-Is_shablon.docx" "02-obsledovanie-i-analiz/" || echo "пропущен: Opisanie_processov_As-Is_shablon.docx"
[ -f "Opisanie_processov_To-Be_shablon.docx" ] && mv "Opisanie_processov_To-Be_shablon.docx" "02-obsledovanie-i-analiz/" || echo "пропущен: Opisanie_processov_To-Be_shablon.docx"
[ -f "Katalog_biznes-trebovaniy_BRD_shablon.docx" ] && mv "Katalog_biznes-trebovaniy_BRD_shablon.docx" "02-obsledovanie-i-analiz/" || echo "пропущен: Katalog_biznes-trebovaniy_BRD_shablon.docx"
[ -f "Reestr_trebovaniy.xlsx" ] && mv "Reestr_trebovaniy.xlsx" "02-obsledovanie-i-analiz/" || echo "пропущен: Reestr_trebovaniy.xlsx"
[ -f "RTM_matrica_trassirovki_shablon.xlsx" ] && mv "RTM_matrica_trassirovki_shablon.xlsx" "02-obsledovanie-i-analiz/" || echo "пропущен: RTM_matrica_trassirovki_shablon.xlsx"
[ -f "Reestr_razryvov_Gap_analiz.xlsx" ] && mv "Reestr_razryvov_Gap_analiz.xlsx" "02-obsledovanie-i-analiz/" || echo "пропущен: Reestr_razryvov_Gap_analiz.xlsx"
[ -f "TZ_golovnoe_shablon.docx" ] && mv "TZ_golovnoe_shablon.docx" "03-proektirovanie/" || echo "пропущен: TZ_golovnoe_shablon.docx"
[ -f "CHTZ_integraciya_shablon.docx" ] && mv "CHTZ_integraciya_shablon.docx" "03-proektirovanie/" || echo "пропущен: CHTZ_integraciya_shablon.docx"
[ -f "CHTZ_dorabotka_shablon.docx" ] && mv "CHTZ_dorabotka_shablon.docx" "03-proektirovanie/" || echo "пропущен: CHTZ_dorabotka_shablon.docx"
[ -f "FRD_funkcionalnye_trebovaniya_shablon.docx" ] && mv "FRD_funkcionalnye_trebovaniya_shablon.docx" "03-proektirovanie/" || echo "пропущен: FRD_funkcionalnye_trebovaniya_shablon.docx"
[ -f "Koncepciya_arhitektury_resheniya_shablon.docx" ] && mv "Koncepciya_arhitektury_resheniya_shablon.docx" "03-proektirovanie/" || echo "пропущен: Koncepciya_arhitektury_resheniya_shablon.docx"
[ -f "Koncepciya_NSI_shablon.docx" ] && mv "Koncepciya_NSI_shablon.docx" "03-proektirovanie/" || echo "пропущен: Koncepciya_NSI_shablon.docx"
[ -f "Koncepciya_migracii_shablon.docx" ] && mv "Koncepciya_migracii_shablon.docx" "03-proektirovanie/" || echo "пропущен: Koncepciya_migracii_shablon.docx"
[ -f "Koncepciya_integracii_shablon.docx" ] && mv "Koncepciya_integracii_shablon.docx" "03-proektirovanie/" || echo "пропущен: Koncepciya_integracii_shablon.docx"
[ -f "Model_dannyh_opisanie_NSI_shablon.docx" ] && mv "Model_dannyh_opisanie_NSI_shablon.docx" "03-proektirovanie/" || echo "пропущен: Model_dannyh_opisanie_NSI_shablon.docx"
[ -f "Rolevaya_model_matrica_prav_shablon.docx" ] && mv "Rolevaya_model_matrica_prav_shablon.docx" "03-proektirovanie/" || echo "пропущен: Rolevaya_model_matrica_prav_shablon.docx"
[ -f "Dizayn_UI_pechatnyh_form_otchetov_shablon.docx" ] && mv "Dizayn_UI_pechatnyh_form_otchetov_shablon.docx" "03-proektirovanie/" || echo "пропущен: Dizayn_UI_pechatnyh_form_otchetov_shablon.docx"
[ -f "Reestr_dorabotok.xlsx" ] && mv "Reestr_dorabotok.xlsx" "04-razrabotka-i-nastroyka/" || echo "пропущен: Reestr_dorabotok.xlsx"
[ -f "Zhurnal_versiy_konfiguracii.xlsx" ] && mv "Zhurnal_versiy_konfiguracii.xlsx" "04-razrabotka-i-nastroyka/" || echo "пропущен: Zhurnal_versiy_konfiguracii.xlsx"
[ -f "Standarty_razrabotki_code_style_shablon.docx" ] && mv "Standarty_razrabotki_code_style_shablon.docx" "04-razrabotka-i-nastroyka/" || echo "пропущен: Standarty_razrabotki_code_style_shablon.docx"
[ -f "Protokol_kod-revyu_shablon.docx" ] && mv "Protokol_kod-revyu_shablon.docx" "04-razrabotka-i-nastroyka/" || echo "пропущен: Protokol_kod-revyu_shablon.docx"
[ -f "Plan_testirovaniya_PMI_shablon.docx" ] && mv "Plan_testirovaniya_PMI_shablon.docx" "05-testirovanie/" || echo "пропущен: Plan_testirovaniya_PMI_shablon.docx"
[ -f "Reestr_test_keysov.xlsx" ] && mv "Reestr_test_keysov.xlsx" "05-testirovanie/" || echo "пропущен: Reestr_test_keysov.xlsx"
[ -f "Protokol_testirovaniya_shablon.docx" ] && mv "Protokol_testirovaniya_shablon.docx" "05-testirovanie/" || echo "пропущен: Protokol_testirovaniya_shablon.docx"
[ -f "Zhurnal_defektov.xlsx" ] && mv "Zhurnal_defektov.xlsx" "05-testirovanie/" || echo "пропущен: Zhurnal_defektov.xlsx"
[ -f "Protokol_priyomochnyh_ispytaniy_shablon.docx" ] && mv "Protokol_priyomochnyh_ispytaniy_shablon.docx" "05-testirovanie/" || echo "пропущен: Protokol_priyomochnyh_ispytaniy_shablon.docx"
[ -f "Plan_razvyortyvaniya_Cutover_shablon.docx" ] && mv "Plan_razvyortyvaniya_Cutover_shablon.docx" "06-vnedrenie-i-ope/" || echo "пропущен: Plan_razvyortyvaniya_Cutover_shablon.docx"
[ -f "Detalnyy_plan_migracii_shablon.docx" ] && mv "Detalnyy_plan_migracii_shablon.docx" "06-vnedrenie-i-ope/" || echo "пропущен: Detalnyy_plan_migracii_shablon.docx"
[ -f "Plan_obucheniya_shablon.docx" ] && mv "Plan_obucheniya_shablon.docx" "06-vnedrenie-i-ope/" || echo "пропущен: Plan_obucheniya_shablon.docx"
[ -f "Reglament_OPE_shablon.docx" ] && mv "Reglament_OPE_shablon.docx" "06-vnedrenie-i-ope/" || echo "пропущен: Reglament_OPE_shablon.docx"
[ -f "Zhurnal_zamechaniy_OPE.xlsx" ] && mv "Zhurnal_zamechaniy_OPE.xlsx" "06-vnedrenie-i-ope/" || echo "пропущен: Zhurnal_zamechaniy_OPE.xlsx"
[ -f "Plan_podderzhki_Hypercare_shablon.docx" ] && mv "Plan_podderzhki_Hypercare_shablon.docx" "06-vnedrenie-i-ope/" || echo "пропущен: Plan_podderzhki_Hypercare_shablon.docx"
[ -f "Rukovodstvo_polzovatelya_shablon.docx" ] && mv "Rukovodstvo_polzovatelya_shablon.docx" "07-ekspluatacionnaya-dokumentaciya/" || echo "пропущен: Rukovodstvo_polzovatelya_shablon.docx"
[ -f "Rukovodstvo_administratora_shablon.docx" ] && mv "Rukovodstvo_administratora_shablon.docx" "07-ekspluatacionnaya-dokumentaciya/" || echo "пропущен: Rukovodstvo_administratora_shablon.docx"
[ -f "Reglamenty_ekspluatacii_SLA_shablon.docx" ] && mv "Reglamenty_ekspluatacii_SLA_shablon.docx" "07-ekspluatacionnaya-dokumentaciya/" || echo "пропущен: Reglamenty_ekspluatacii_SLA_shablon.docx"
[ -f "Instrukcii_po_tipovym_operaciyam_shablon.docx" ] && mv "Instrukcii_po_tipovym_operaciyam_shablon.docx" "07-ekspluatacionnaya-dokumentaciya/" || echo "пропущен: Instrukcii_po_tipovym_operaciyam_shablon.docx"
[ -f "Akt_sdachi-priyomki_shablon.docx" ] && mv "Akt_sdachi-priyomki_shablon.docx" "08-zakrytie/" || echo "пропущен: Akt_sdachi-priyomki_shablon.docx"
[ -f "Protokol_zaversheniya_proekta_shablon.docx" ] && mv "Protokol_zaversheniya_proekta_shablon.docx" "08-zakrytie/" || echo "пропущен: Protokol_zaversheniya_proekta_shablon.docx"
[ -f "Otchet_ob_izvlechyonnyh_urokah_shablon.docx" ] && mv "Otchet_ob_izvlechyonnyh_urokah_shablon.docx" "08-zakrytie/" || echo "пропущен: Otchet_ob_izvlechyonnyh_urokah_shablon.docx"
[ -f "Reestr_peredannyh_aktivov.xlsx" ] && mv "Reestr_peredannyh_aktivov.xlsx" "08-zakrytie/" || echo "пропущен: Reestr_peredannyh_aktivov.xlsx"

echo "Готово. Файлы разложены по папкам фаз."